name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  # Remove pull_request trigger since we don't want to deploy PRs
  
  # Keeps the manual trigger option
  workflow_dispatch:

# Add permissions configuration
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add condition to only run on push to main or manual trigger
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: .
        run: npm ci

      - name: Build website
        working-directory: .
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist  # Change this to your build output directory (commonly 'dist' or 'build')
          branch: gh-pages
          clean: true
