name: GitHub Pages Deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [content-update]

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  update-content:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Update Content
        env:
          CONTENT_UPDATE: ${{ github.event.client_payload.content }}
          PAGE_ID: ${{ github.event.client_payload.pageId }}
        run: |
          mkdir -p "src/pages/$(dirname ${PAGE_ID})"
          echo "$CONTENT_UPDATE" > "src/pages/${PAGE_ID}.html"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update content for ${{ github.event.client_payload.pageId }}"
          git push origin main

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [update-content]
    if: success() || github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build website
        env:
          BASE_URL: '/portfolio'
        run: |
          npm run build
          cp dist/index.html dist/404.html

      # Deploy to gh-pages branch to preserve file structure
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true

      # Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4