name: GitHub Pages Deployment

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update Cursor rules
        run: npm run update-cursor-rules

      - name: Commit updated rules (if changed)
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .cursor/rules .cursor/.cursorrules
          git diff --staged --quiet || git commit -m "Auto-update Cursor rules [skip ci]"
          git push || echo "No changes to push"

      - name: Build website and Storybook
        env:
          BASE_URL: '/portfolio'
        run: |
          npm run build
          npm run build-storybook
          cp dist/index.html dist/404.html

      # Combine website and Storybook builds
      - name: Prepare combined deployment
        run: |
          # Move Storybook build into dist/storybook
          mv dist/storybook dist/storybook-temp
          mkdir -p dist/storybook
          mv dist/storybook-temp/* dist/storybook/

      # Add CNAME file for custom domain
      - name: Add CNAME file for custom domain
        run: echo 'bobbieallsop.co.uk' > dist/CNAME

      # Deploy to gh-pages branch to preserve file structure
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true

      # Deploy to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4